spring:
  application:
    name: we-bid
  cloud:
    vault:
      token: ${VAULT_TOKEN:hvs.pBkMcZxHDTH7lyANLuueKG0k}
      scheme: http
      port: 8200
      kv:
        enabled: true
  config:
    import: vault://
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54320/webid}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username:tahamr08@gmail.com}
    password: ${mail.password:123}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    include-message: always


logging:
  level:
    org:
      springframework:
        security: DEBUG
